#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-CMake.yml
name: TensorRT RTX

env:
  GH_TOKEN: ${{github.token}}
  Branch: ${{github.ref_name}}
  Artifacts: build/Release
  Title: ${{github.event.repository.name}}
  Executable: ${{github.event.repository.name}}.exe # *

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  Build:
    name: ${{matrix.Settings.Name}}-${{matrix.Configuration}}
    runs-on: windows-2022
    strategy:
      matrix:
        Configuration: [Release] #[Release, Debug]
        Settings:
#        - {
#            Name: "Win32",
#            Platform: "Win32",
#            Architecture: "x86",
#            Triplet: "x86-windows"
#          }
        - {
            Name: "Win64",
            Platform: "x64",
            Architecture: "x64",
            Triplet: "x64-windows"
          }
          
    steps:

    - name: Clone repo and submodules
      run: >
        git
        clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git
        "${{github.workspace}}"
        --branch ${{env.Branch}}
        --recurse-submodules
#--depth 1 - Fetches single commit which is faster but breaks commit count

    - name: Get current date, commit hash and count
      run: |
        echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
        echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV

    - name: Print PATH A
      run: |
        echo A1 "$Env:Path"
        echo A2 "${{env.PATH}}"

    - name: Cache CUDA
      id: cache-cuda
      uses: actions/cache@v5
      with:
        path: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9"
        key: CUDA_V12_9
    - name: Download CUDA
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      run: |
        curl --ssl-revoke-best-effort -L "https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda_12.9.1_576.57_windows.exe" -o "CUDA.exe"
    - name: Install CUDA
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      run: |
        Start-Process -Wait "CUDA.exe" -ArgumentList "-s"

    - name: Set CUDA path
      run: |
        echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
        echo "CUDA_PATH_V12_9=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
        echo "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
        Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin"
        Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin\x64"
        echo "PATH=$Env:Path" >> $env:GITHUB_ENV
#        echo "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin\x64;$Env:Path" >> $env:GITHUB_ENV


    - name: Cache cuDNN
      id: cache-cudnn
      uses: actions/cache@v5
      with:
        path: "C:\\Program Files\\NVIDIA\\CUDNN\\v9.20"
        key: CUDNN_V9_20
    - name: Download cuDNN
      if: steps.cache-cudnn.outputs.cache-hit != 'true'
      run: |
        curl --ssl-revoke-best-effort -L "https://developer.download.nvidia.com/compute/cudnn/9.20.0/local_installers/cudnn_9.20.0_windows_x86_64.exe" -o "cuDNN.exe"
    - name: Install cuDNN
      if: steps.cache-cudnn.outputs.cache-hit != 'true'
      run: |
        Start-Process -Wait "cuDNN.exe" -ArgumentList "-s"
    - name: Set cuDNN path
      run: |
        echo "CUDNN_PATH=C:\Program Files\NVIDIA\CUDNN\v9.20" >> $env:GITHUB_ENV
        echo "CUDNN_HOME=C:\Program Files\NVIDIA\CUDNN\v9.20" >> $env:GITHUB_ENV
        Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\NVIDIA\CUDNN\v9.20\bin\12.9\x64"
        echo "PATH=$Env:Path" >> $env:GITHUB_ENV
