#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-CMake.yml
name: TensorRT RTX

env:
  GH_TOKEN: ${{github.token}}
  Branch: ${{github.ref_name}}
  Artifacts: build/Release
  Title: ${{github.event.repository.name}}
  Executable: ${{github.event.repository.name}}.exe # *

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  Build:
    name: ${{matrix.Settings.Name}}-${{matrix.Configuration}}
    runs-on: windows-2022
    strategy:
      matrix:
        Configuration: [Release] #[Release, Debug]
        Settings:
#        - {
#            Name: "Win32",
#            Platform: "Win32",
#            Architecture: "x86",
#            Triplet: "x86-windows"
#          }
        - {
            Name: "Win64",
            Platform: "x64",
            Architecture: "x64",
            Triplet: "x64-windows"
          }
          
    steps:

    - name: Clone repo and submodules
      run: >
        git
        clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git
        "${{github.workspace}}"
        --branch ${{env.Branch}}
        --recurse-submodules
#--depth 1 - Fetches single commit which is faster but breaks commit count

    - name: Get current date, commit hash and count
      run: |
        echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
        echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV

    - name: Print PATH A
      run: |
        echo A1 "$Env:Path"
        echo A2 "${{env.PATH}}"

    - name: Cache CUDA
      id: cache-cuda
      uses: actions/cache@v5
      with:
        path: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9"
        key: CUDA_V12_9
    - name: Download CUDA
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      run: |
        curl --ssl-revoke-best-effort -L "https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda_12.9.1_576.57_windows.exe" -o "CUDA.exe"
    - name: Install CUDA
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      run: |
        Start-Process -Wait "CUDA.exe" -ArgumentList "-s"

    - name: Set CUDA path
      run: |
        echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
        echo "CUDA_PATH_V12_9=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
        echo "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
        Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin"
#        echo "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin\x64;$Env:Path" >> $env:GITHUB_ENV






#    - name: Cache cuDNN
#      id: cache-cudnn
#      uses: actions/cache@v5
#      with:
#        path: "C:\\Program Files\\NVIDIA\\CUDNN\\v9.19"
#        key: CUDNN_V9_19
#    - name: Download cuDNN
#      if: steps.cache-cudnn.outputs.cache-hit != 'true'
#      run: |
#        curl --ssl-revoke-best-effort -L "https://developer.download.nvidia.com/compute/cudnn/9.19.1/local_installers/cudnn_9.19.1_windows_x86_64.exe" -o "cuDNN.exe"
#    - name: Install cuDNN
#      if: steps.cache-cudnn.outputs.cache-hit != 'true'
#      run: |
#        Start-Process -Wait "cuDNN.exe" -ArgumentList "-s"
# NOTE: STORING CACHE REQUIRES THE RUN TO SUCCEED, SO IF IT'S FAILING, TRY TEMPORARILY REMOVING ALL THE STEPS BELOW THIS LINE

#    - name: Install vcpkg
#      uses: lukka/run-vcpkg@v11.5
#      with:
#        vcpkgGitCommitId: c2aeddd80357b17592e59ad965d2adf65a19b22f
#    - name: Install dependencies
#      run: |
#        vcpkg install 

    - name: Print PATH B
      run: |
        echo B1 "$Env:Path"
        echo B2 "${{env.PATH}}"

    - name: Download Dependencies
      run: |
        curl --ssl-revoke-best-effort --create-dirs -L "https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/1.1/TensorRT-RTX-1.1.1.26.Windows.win10.cuda-12.9.zip" -o "TensorRT-RTX.zip"
        7z x "TensorRT-RTX.zip"
        Add-Content -Path $env:GITHUB_PATH -Value "${{github.workspace}}\TensorRT-RTX-1.1.1.26\lib"
#        $Env:Path = "${{github.workspace}}\TensorRT-RTX-1.1.1.26\lib;" + $Env:Path

    - name: Print PATH C
      run: |
        echo C1 "$Env:Path"
        echo C2 "${{env.PATH}}"

    - name: List files
      run: ls -R

    - name: Build
      run: >
        .\build.bat
        --config Release
        --build_dir build
        --parallel
        --use_nv_tensorrt_rtx
        --tensorrt_rtx_home "${{github.workspace}}\TensorRT-RTX-1.1.1.26"
        --cuda_home "${{env.CUDA_PATH}}"
        --cmake_generator "Visual Studio 17 2022"
        --build_shared_lib
        --skip_tests
        --build
        --update
        --use_vcpkg
        --cmake_extra_defines CMAKE_CUDA_COMPILER="${{env.CUDA_PATH}}bin\nvcc.exe"

    - name: List files
      run: ls -R

#    - name: Deploy
#      shell: cmd
#      run: |
#        windeployqt.exe "${{github.workspace}}/${{env.Artifacts}}/${{env.Executable}}"
#        If exist "vcpkg\installed\${{matrix.Settings.Platform}}-windows\bin\*.dll"       (copy "vcpkg\installed\${{matrix.Settings.Platform}}-windows\bin\*.dll"       "${{env.Artifacts}}")
#        If exist "vcpkg_installed\${{matrix.Settings.Platform}}-windows\bin\*.dll"       (copy "vcpkg_installed\${{matrix.Settings.Platform}}-windows\bin\*.dll"       "${{env.Artifacts}}")
#        If exist "vcpkg\installed\${{matrix.Settings.Platform}}-windows\debug\bin\*.dll" (copy "vcpkg\installed\${{matrix.Settings.Platform}}-windows\debug\bin\*.dll" "${{env.Artifacts}}")
#        If exist "vcpkg_installed\${{matrix.Settings.Platform}}-windows\debug\bin\*.dll" (copy "vcpkg_installed\${{matrix.Settings.Platform}}-windows\debug\bin\*.dll" "${{env.Artifacts}}")
#        xcopy "assets\" "${{env.Artifacts}}\assets\" /s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.Title}}-${{matrix.Settings.Name}}-${{matrix.Configuration}}
        path: "${{github.workspace}}/${{env.Artifacts}}/"

  Release:
    name: Release
    runs-on: windows-latest
    needs: Build
    steps:

      - name: Clone repo and submodules
        run: git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git "${{github.workspace}}" --branch ${{env.Branch}} --recurse-submodules

      - name: Get current date, commit hash and count
        run: |
          echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
          echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
          echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
          echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
          echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV

#      - name: Download Artifacts - Win32
#        uses: actions/download-artifact@v4
#        with:
#          name: ${{env.Title}}-Win32-Release
#          path: Release/Win32/

      - name: Download Artifacts - Win64
        uses: actions/download-artifact@v4
        with:
          name: ${{env.Title}}-Win64-Release
          path: Release/Win64/

      - name: Deploy
        run: |
          cp "README.md" "Release/ReadMe.txt"
          cp "LICENSE" "Release/License.txt"
  
      - name: Compress artifacts
        if: github.event_name == 'push'
        run: |
          7z a "Release/${{env.Title}}.zip" "${{github.workspace}}/Release/*" -mx=9
          cp "Release/${{env.Title}}.zip" "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"
  
      - name: Purge tag - latest-${{env.Branch}}
        if: github.event_name == 'push'
        run: |
          gh release delete latest-${{env.Branch}} --repo ${{github.repository}} --cleanup-tag --yes || true
  
      - name: Release - archive-${{env.Branch}}
        if: github.event_name == 'push'
        run: |
          gh release create archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
          Build logs: https://github.com/${{github.repository}}/actions" || true
          gh release edit archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
          Build logs: https://github.com/${{github.repository}}/actions" || true
          gh release upload archive-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"
  
      - name: Release - latest-${{env.Branch}}
        if: github.event_name == 'push'
        run: |
          gh release create latest-${{env.Branch}} --repo ${{github.repository}} --target ${{env.CommitHash}} --generate-notes --latest=true --title "${{env.Title}} r${{env.CommitCount}}@${{env.CommitHashShort}}" --notes "Build archive: https://github.com/${{github.repository}}/releases/tag/archive-${{env.Branch}}
          Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          gh release upload latest-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}.zip"